### PR TITLE
I2C: Implement asynch I2C for STM32F4.

### PR DESCRIPTION
**Pull request by niklas-arm**
This port has several caveats:
- No DMA support, only interrupt based,
- start-write(n)-restart-read(m)-stop is only supported for n=1,2 due to
  the CubeF4 library not providing a generic solution for this,
- start-stop (i.e. "pinging" a device) not supported due to the CubeF4
  library not allowing transfer sizes of zero,
- all CubeF4 `*_IT` functions perform blocking actions (but with timeout)
  in the `i2c_transfer_asynch` method :
	- generating a start condition
	- writing the device address
	- writing the first 1 or 2 bytes, then restart in write(n)-read(m) cases
  As a result, if a failure occurs during these blocking parts of the
  transfer, no callback can be generated, i.e. there is a silent failure.

This code passes our mbed-hal unit tests, however, only barely, since the tests only test write(n) and write(2)-read(m) transfers.

This depends on https://github.com/ARMmbed/mbed-hal-st-stm32f429zi/pull/14.

@bogdanm @0xc0170 @bremoran

### CODE REVIEW

**Comment by 0xc0170** [comment]
>
- blocking actions
- no ping
- start-write(n)-restart-read(m)-stop is only supported for n=1,2

:tired_face: Are these acceptable? They provide HAL, as they used _HAL functions in their ports. Isn't this time to swich? How much extra work as result?

If we have tests, they would be failing all over

**Comment by niklas-arm** [comment]
> :tired_face: Are these acceptable?

Of course not.

I would like to avoid writing a manual state machine for ST's I2C hardware.
I've done it before and it is not fun, but I think it is unavoidable.

However, and this is important: **Until we have not designed an interface for a platform-independend I2C state machine, there is no point investing any effort into this**.
I especially want to avoid doing the work twice, once for implementing the current HAL, and again for implementing the new HAL.

There is a better option: Use a shim layer.
So, we would design a new HAL level I2C API, and implement it, but use a inside the F4 hal module to translate this to the current HAL.
This way we only do the manual work once and can still service both HALs.

Deal?

**Comment by 0xc0170** [comment]
@niklas-arm is it worth adding this to a current code base? There's some refactoring here, I would say yes, however we won't enable i2c async, because of reasons above?

**Comment by niklas-arm** [comment]
Let me put it this way: If you want `AsyncI2C` this is the best I can give you with using the CubeF4 lib.

**Comment by 0xc0170** [comment]
Please rebase this PR

**Comment by niklas-arm** [comment]
Ping @0xc0170. This is rebased.

**Comment by 0xc0170** [comment]
The object i2c has not been updated, https://github.com/niklas-arm/mbed-hal-st-stm32f4/blob/feature/async_i2c/mbed-hal-st-stm32f4/objects.h#L90, this fails to build

**Pull request closed without merging**
