### PR TITLE
[NUCLEO_F401RE] add asynchronous I2C

### PR DESCRIPTION
**Pull request by dbestm**

### CODE REVIEW

**Comment by 0xc0170** [comment]
How this differs from #17 ? There were some problems identified by that PR, thus was put on hold.

**Comment by dbestm** [comment]
DMA is used and the stop management feature is available.

**Comment by dbestm** [comment]
the possibility to send frame with no data also.

**Comment by betzw** [comment]
Pls. refer to my comments in https://github.com/ARMmbed/mbed-hal-st-stm32f401re/commit/250412495ca0164ffc70c25a906cb52063934a22!

**Comment by bcostm** [comment]
No objection to merge this PR ? The F401 build is fail today without it.

**Comment by betzw** [comment]
I think there is a problem around the macro `MODULE_SIZE_I2C` wich should be written with an additional "S" like `MODULE_SIZE_I2C` in order to not break the compilation of mbed-drivers anymore (for more information pls. refer to https://github.com/ARMmbed/mbed-hal-st-stm32f401re/commit/250412495ca0164ffc70c25a906cb52063934a22)!!!
Furthermore, the definition of this macro must be made in some header file which gets also included by `mbed-drivers` e.g. `target_config.h`.

**Pull request merged**
